### ISSUE TITLE
[1.10.2] modid name mismatch

### ISSUE THREAD

**Issue by Morpheus1101** [AstroDevelopment/Astro-Lib#1]
mods require astrolib but the build filename and modid is lib so anything depending on astrolib breaks as forge cant find the dependant.

![mmd](https://cloud.githubusercontent.com/assets/10524952/19414035/5bba2d1c-9384-11e6-96f1-224aa814c8a4.png)

**Comment by TheCodedOne** [comment]
you know i know of this -_-

**Comment by Morpheus1101** [comment]
Im being proper and thorough and putting it here, just incase u forget :P

**Comment by TheCodedOne** [comment]
this was caused by the upload uploading the wrong damn file :/ .. used an old version will fix soon
